Demo.Presentation.Layer/Demo.Presentation.Layer/Models/ErrorViewModel.cs
namespace Demo.Presentation.Layer.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Demo.Presentation.Layer/Demo.Presentation.Layer/ViewModels/EmployeeViewModel.cs
using System.ComponentModel.DataAnnotations;
using Demo.Data.Access.Layer.Models;

namespace Demo.Presentation.Layer.ViewModels;

public class EmployeeViewModel
{
    public int Id { get; set; }
    [StringLength(maximumLength: 50 , MinimumLength = 5)]
    public string Name { get; set; }
    [Range(19,60)]
    public int Age { get; set; }
    
    public string Address { get; set; }
    [DataType(DataType.Currency)]
    public decimal Salary { get; set; }
    [EmailAddress]
    public string Email { get; set; }
    [Phone]
    public string Phone { get; set; }
    public bool IsActive { get; set; }
    public Department? Department { get; set; }
    public int? DepartmentId { get; set; }

}

Demo.Presentation.Layer/Demo.Presentation.Layer/ViewModels/ErrorViewModel.cs
namespace Demo.Presentation.Layer.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Controllers/DepartmentsController.cs
using Business.Logic.Layer.Interfaces;
using Demo.Data.Access.Layer.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Presentation.Layer.Controllers;

public class DepartmentsController : Controller
{
    // private readonly IGenaricRepository<Department> _repository;
    private readonly IDepartmentRepository _repository;
    public DepartmentsController(IDepartmentRepository departmentRepository)
    {
        _repository = departmentRepository;
    }
    
    [HttpGet]
    public IActionResult Index()
    {
        var departments = _repository.GetAll();
        return View(departments);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Department department)
    {
        if (ModelState.IsValid)
        {
            _repository.Create(department);
            return RedirectToAction("Index");
        }
        return View(department);
    }

    public IActionResult Details(int? id) => DepartmentControlHandler(id , nameof(Details));
    
    public IActionResult Edit(int? id) => DepartmentControlHandler(id , nameof(Edit));
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit([FromRoute]int id,Department department)
    {
        if(id != department.Id) return BadRequest();
        try
        {
            if (ModelState.IsValid)
            {
                _repository.Update(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
        }
        return View(department);
    }
    public IActionResult Delete(int? id) => DepartmentControlHandler(id , nameof(Delete));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult ConfirmDelete(int? id)
    {
        var department = _repository.Get(id.Value);
        if(department == null) return NotFound();
        _repository.Delete(department);
        return RedirectToAction("Index");
    }
    
    private IActionResult DepartmentControlHandler(int? id , string viewName)
    {
        if(!id.HasValue) return BadRequest();
        var department = _repository.Get(id.Value);
        if(department == null) return NotFound();
        return View(viewName , department);
    }
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Controllers/EmployeesController.cs
using AutoMapper;
using Business.Logic.Layer.Interfaces;
using Demo.Data.Access.Layer.Models;
using Demo.Presentation.Layer.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Demo.Presentation.Layer.Controllers;

public class EmployeesController : Controller
{
    private readonly IMapper _mapper;
    private readonly IUnitOfWork _repository;

    public EmployeesController(IUnitOfWork repository, IMapper mapper)
    {
        _repository = repository;
        _mapper = mapper;
    }

    public IActionResult Index(string? searchValue)
    {
        var employees = Enumerable.Empty<Employee>();
        if (string.IsNullOrEmpty(searchValue))
            employees = _repository.Employees.GetAllWithDepartment();
        else
            employees = _repository.Employees.GetAllByName(searchValue);
        var employeesVM = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
        return View(employeesVM);
    }

    public IActionResult Create()
    {
        var departments = _repository.Departments.GetAll();
        SelectList departmentsList = new SelectList(departments, "Id", "Name");
        ViewBag.Departments = departmentsList;
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(EmployeeViewModel employeeVM)
    {
        if (ModelState.IsValid)
        {
            var employee = _mapper.Map<Employee>(employeeVM);
            _repository.Employees.Create(employee);
            _repository.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(employeeVM);
    }
    public IActionResult Details(int? id) => EmployeeControlHandler(id , nameof(Details));
    public IActionResult Edit(int? id) => EmployeeControlHandler(id , nameof(Edit));
    public IActionResult Delete(int? id) => EmployeeControlHandler(id , nameof(Delete));
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult ConfirmDelete(int? id)
    {
        var employee = _repository.Employees.Get(id.Value);
        if(employee == null) return NotFound();
        _repository.Employees.Delete(employee);
        _repository.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit([FromRoute] int id, EmployeeViewModel employeeVM)
    {
        if (id != employeeVM.Id) return BadRequest();
        try
        {
            if (ModelState.IsValid)
            {
                var employee = _mapper.Map<Employee>(employeeVM);
                _repository.Employees.Update(employee);
                if (_repository.SaveChanges() > 0)
                {
                    TempData["Success"] = $"Employee {employeeVM.Name} Updated Successfully";
                }
                return RedirectToAction("Index");
            }
            return View(employeeVM);
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
        }
        return View(employeeVM);
        
    }
    private IActionResult EmployeeControlHandler(int? id , string viewName)
    {
        if (viewName == nameof(Edit))
        {
            var departments = _repository.Departments.GetAll();
            SelectList departmentsList = new SelectList(departments, "Id", "Name");
            ViewBag.Departments = departmentsList;
        }
        if(!id.HasValue) return BadRequest();
        var employee = _repository.Employees.Get(id.Value);
        if(employee == null) return NotFound();
        var employeeVM = _mapper.Map<EmployeeViewModel>(employee);
        return View(viewName , employeeVM);
    }
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Demo.Presentation.Layer.ViewModels;

namespace Demo.Presentation.Layer.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Departments/Create.cshtml
@model Demo.Data.Access.Layer.Models.Department

@{
    ViewBag.Title = "Create";
    Layout = "_Layout";
}

<h2>Create New Department</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Code" class="control-label"></label>
        <input asp-for="Code" class="form-control" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreatedDate" class="control-label"></label>
        <input asp-for="CreatedDate" class="form-control" />
        <span asp-validation-for="CreatedDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Departments/Delete.cshtml
@model Demo.Data.Access.Layer.Models.Department

@{
    ViewBag.Title = "Delete Department";
    Layout = "_Layout";
}

<h2>Delete Department</h2>

<h3>Are you sure you want to delete this department?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Code
        </dt>
        <dd class="col-sm-10">
            @Model.Code
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Created Date
        </dt>
        <dd class="col-sm-10">
            @Model.CreatedDate
        </dd>
    </dl>
</div>

<form asp-action="ConfirmDelete">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Departments/Details.cshtml
@model Demo.Data.Access.Layer.Models.Department

@{
    ViewBag.Title = "Department Details";
    Layout = "_Layout";
}

<h2>@Model.Name Department Details</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Code
        </dt>
        <dd class="col-sm-10">
            @Model.Code
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Created Date
        </dt>
        <dd class="col-sm-10">
            @Model.CreatedDate
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Departments/Edit.cshtml
@model Demo.Data.Access.Layer.Models.Department

@{
    ViewBag.Title = "Edit Department";
    Layout = "_Layout";
}

<h2>Edit Department</h2>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="Code" class="control-label"></label>
        <input asp-for="Code" class="form-control" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreatedDate" class="control-label"></label>
        <input asp-for="CreatedDate" class="form-control" />
        <span asp-validation-for="CreatedDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Departments/Index.cshtml
@model IEnumerable<Demo.Data.Access.Layer.Models.Department>

@{
    ViewData["Title"] = "Index";
}

<a asp-controller="Departments" asp-action="Create" class="btn btn-primary mb-3">Create New Department</a>
@if (!Model.Any())
{
    <div class="mt-5 alert-warning">
        <h2>There is no Department</h2>
    </div>
}
else
{
    <h1>All Departments</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Created Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var department in Model)
            {
                <tr>
                    <td>@department.Code</td>
                    <td>@department.Name</td>
                    <td>@department.CreatedDate</td>
                    <partial name="_ButtonsPartialView" model="@department.Id"/><partial/>
                </tr>
            }
        </tbody>
    </table>
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/Create.cshtml
@model EmployeeViewModel

@{
    ViewBag.Title = "Create";
    Layout = "_Layout";
}

<h2>Create New Employee</h2>

<form asp-action="Create">
    <partial name="PartialViews/CreateEditPartial" model="@Model"/>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary"/>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>

@section Validation {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/Delete.cshtml
@model EmployeeViewModel
        
        @{
            ViewBag.Title = "Delete Employee";
            Layout = "_Layout";
        }
        
        <h2>Delete Employee</h2>
        
        <h3>Are you sure you want to delete this employee?</h3>
        
        <div>
            <hr />
            <partial name="PartialViews/DetailsDeletePartial" model="Model" /><partial/>
        </div>
        
        <form asp-action="ConfirmDelete">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/Details.cshtml
@model EmployeeViewModel
        
        @{
            ViewBag.Title = "Employee Details";
            Layout = "_Layout";
        }
        
        <h2>@Model.Name Employee Details</h2>
        
        <div>
            <hr />
            <partial name="PartialViews/DetailsDeletePartial"/><partial/>
        </div>
        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/Edit.cshtml
@model EmployeeViewModel
        
        @{
            ViewBag.Title = "Edit Employee";
            Layout = "_Layout";
        }
        
        <h2>Edit Employee</h2>
        
        <form asp-action="Edit">
            <partial name="PartialViews/CreateEditPartial" model="@Model"/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/Index.cshtml
@model IEnumerable<EmployeeViewModel>

@{
    ViewBag.Title = "Employees List";
    Layout = "_Layout";
}
<h1>@TempData["Success"]</h1>

<h2>Employees List</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<div class="mt-2">
    <form asp-action="Index" class="row offset-1">
        <div class="col-10">
            <input class="form-control" type="text" placeholder="Employee's Name" name="SearchValue" required="required"/>
        </div>
        <div class="col-2">
            <input class="btn btn-info" type="submit" value="Search"/>
        </div>
    </form>
</div>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department!.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <span style="color:@(item.IsActive ? "green" : "red")">&#9679;</span> 
            </td>
            <partial name="_ButtonsPartialView" model="@item.Id"/><partial/>
        </tr>
    }
    </tbody>
</table>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/PartialViews/CreateEditPartial.cshtml
@model EmployeeViewModel
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control"/>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Age" class="control-label"></label>
    <input asp-for="Age" class="form-control"/>
    <span asp-validation-for="Age" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control"/>
    <span asp-validation-for="Address" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Salary" class="control-label"></label>
    <input asp-for="Salary" class="form-control"/>
    <span asp-validation-for="Salary" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Department"></label>
    <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.Departments">
        <option value="@null">Select Department</option>
    </select>
</div>
<div class="form-group">
    <label asp-for="Email" class="control-label"></label>
    <input asp-for="Email" class="form-control"/>
    <span asp-validation-for="Email" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Phone" class="control-label"></label>
    <input asp-for="Phone" class="form-control"/>
    <span asp-validation-for="Phone" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="IsActive" class="control-label"></label>
    <input asp-for="IsActive" type="checkbox" class="form-check"/>
    <span asp-validation-for="IsActive" class="text-danger"></span>
</div>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Employees/PartialViews/DetailsDeletePartial.cshtml
@model EmployeeViewModel

<dl class="row">
    <dt class="col-sm-2">
        Name
    </dt>
    <dd class="col-sm-10">
        @Model.Name
    </dd>
    <dt class="col-sm-2">
        Age
    </dt>
    <dd class="col-sm-10">
        @Model.Age
    </dd>
    <dt class="col-sm-2">
        Address
    </dt>
    <dd class="col-sm-10">
        @Model.Address
    </dd>
    <dt class="col-sm-2">
        Salary
    </dt>
    <dd class="col-sm-10">
        @Model.Salary
    </dd>
    <dt class="col-sm-2">
        Department
    </dt>
    <dd class="col-sm-10">
        @Model.Department?.Name
    </dd>
    <dt class="col-sm-2">
        Email
    </dt>
    <dd class="col-sm-10">
        @Model.Email
    </dd>
    <dt class="col-sm-2">
        Phone
    </dt>
    <dd class="col-sm-10">
        @Model.Phone
    </dd>
    <dt class="col-sm-2">
        Is Active
    </dt>
    <dd class="col-sm-10">
        @Model.IsActive
    </dd>
</dl>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Shared/_ButtonsPartialView.cshtml
@model int
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-warning">Edit</a> |
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-info">Details</a> |
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">Delete</a>
</td>

Demo.Presentation.Layer/Demo.Presentation.Layer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVC DEMO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Demo.Presentation.Layer.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.Presentation.Layer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Demo.Presentation.Layer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Validation", required: false)
</body>
</html>